name: Site of Seasons
markdown: redcarpet
url: http://cmc333333.github.io/jekyll-example
redcarpet:
  extensions:
    - tables
pygments: true
prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          type: "text"
      - name: "season"
        field: 
          element: "select"
          label: "Season"
          options:
            - name: 'Spring'
              value: 'spring'
            - name: 'Summer'
              value: 'summer'
            - name: 'Fall'
              value: 'fall'
            - name: 'Winter'
              value: 'winter'
      - name: "reviewed"
        field:
          element: "checkbox"
          label: "Reviewed"
          value: false
